# Generated by Django 2.2.19 on 2022-09-20 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_color', message='Укажите значение в HEX формате!', regex='#[A-Fa-f0-9]{6}')], verbose_name='Цвет(в HEX)'),
        ),
    ]
